# Generated by Django 4.1.2 on 2022-11-23 10:12

import AdmissionSystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConventionalStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_no", models.CharField(blank=True, max_length=199, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                ("cnic_or_B_form_No", models.CharField(max_length=100)),
                ("father_Name", models.CharField(max_length=100)),
                ("father_income", models.CharField(max_length=100)),
                ("father_occupation", models.CharField(max_length=100)),
                (
                    "class_of_interest",
                    models.CharField(blank=True, max_length=199, null=True),
                ),
                ("mobileno", models.CharField(max_length=100)),
                ("domicile", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("religion", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("present_address", models.CharField(max_length=100)),
                ("sport_person", models.BooleanField()),
                ("hafiz", models.BooleanField()),
                ("disability", models.BooleanField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=20,
                    ),
                ),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("Contacted Virtually", "Contacted Virtually"),
                            ("Reception Appearance", "Reception Interview"),
                            ("Internal Interview", "Internal Interview"),
                            ("External Interview", "External Interview"),
                            ("Admitted", "Admitted"),
                            ("Rejected", "Rejected"),
                            ("Drop out", "Drop out"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program", models.CharField(max_length=100)),
                ("institute", models.CharField(max_length=100)),
                ("semester", models.CharField(max_length=100)),
                ("start_timings", models.TimeField()),
                ("end_timings", models.TimeField()),
                ("institute_Address", models.CharField(max_length=100)),
                ("CGPA", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="ShortCourseName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=100)),
                ("course_duration", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.currentstudy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_no", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "photograph",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=AdmissionSystem.models.SkillStudent.student_directory_path,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=100
                    ),
                ),
                ("father_Name", models.CharField(max_length=100)),
                (
                    "cnic_or_B_form_No",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("domicile", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(null=True)),
                (
                    "pre_qualification",
                    models.CharField(
                        choices=[
                            ("Matric", "Matric"),
                            ("Inter", "Inter"),
                            ("Bachelor", "Bachelor"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "residencial_status",
                    models.CharField(
                        choices=[("Hostel", "Hostel"), ("Local", "Local")],
                        max_length=100,
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("laptop", models.BooleanField()),
                ("computer_at_Home", models.BooleanField()),
                (
                    "shift",
                    models.CharField(
                        choices=[("Morning", "Morning"), ("Evening", "Evening")],
                        max_length=20,
                    ),
                ),
                (
                    "program_of_interest",
                    models.CharField(
                        choices=[
                            ("Artifical Intelligence", "Artifical Intelligence"),
                            ("Big Data", "Big Data"),
                            ("Graphics Designing", "Graphics Designing"),
                            ("Icom_Part_1", "Icom_Part_1"),
                            ("Icom_Part_2", "Icom_Part_2"),
                            ("Bcom_Part_1", "Bcom_Part_1"),
                            ("Bcom_Part_2", "Bcom_Part_2"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "transportation",
                    models.CharField(
                        choices=[
                            ("Bike", "Bike"),
                            ("Parent_Drops", "Parent_Drops"),
                            ("Local Transport", "Local Transport"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("Contacted Virtually", "Contacted Virtually"),
                            ("Reception Appearance", "Reception Interview"),
                            ("Internal Interview", "Internal Interview"),
                            ("External Interview", "External Interview"),
                            ("Admitted", "Admitted"),
                            ("Rejected", "Rejected"),
                            ("Drop out", "Drop out"),
                        ],
                        default="Pending",
                        max_length=100,
                    ),
                ),
                ("created_by", models.CharField(default="None", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShortCoursesTaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("Private", "Private"),
                            ("NAVTTC", "NAVTTC"),
                            ("PSDA", "PSDA"),
                            ("TEVTA", "TEVTA"),
                            ("Digiskill", "Digiskill"),
                            ("PIAIC", "PIAIC"),
                        ],
                        max_length=100,
                    ),
                ),
                ("institute_name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "course_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AdmissionSystem.shortcoursename",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.skillstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Personal_Phone_no", models.CharField(max_length=100)),
                ("Father_Phone_no", models.CharField(max_length=100)),
                ("Mother_Phone_no", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.skillstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.skillstudent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("start_timings", models.TimeField(blank=True, null=True)),
                ("end_timings", models.TimeField(blank=True, null=True)),
                ("salary", models.CharField(max_length=100)),
                ("company_address", models.CharField(max_length=100)),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.jobposition",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.skillstudent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="currentstudy",
            name="student",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="AdmissionSystem.skillstudent",
            ),
        ),
        migrations.CreateModel(
            name="Contacted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("reply", models.TextField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="AdmissionSystem.skillstudent",
                    ),
                ),
            ],
        ),
    ]
