# Generated by Django 4.1.2 on 2022-11-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdmissionSystem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phoneno",
            old_name="Personal_Phone_no",
            new_name="Emergency_Phone_no",
        ),
        migrations.AddField(
            model_name="phoneno",
            name="Personal_Phone_no_1",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="phoneno",
            name="Personal_Phone_no_2",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
