# Generated by Django 4.1.2 on 2022-11-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "AdmissionSystem",
            "0002_rename_personal_phone_no_phoneno_emergency_phone_no_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="skillstudent",
            name="date_applied",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortcoursename",
            name="student",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="AdmissionSystem.skillstudent",
            ),
        ),
    ]
