# Generated by Django 4.0.4 on 2022-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0003_skillstudent_date_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstudent',
            name='information_source',
            field=models.CharField(choices=[('Random Walk-in', 'Random Walk-in'), ('Social Media', 'Social Media'), ('By Reference', 'By Reference'), ('Electronic Media', 'Electronic Media'), ('On-Ground Advertisement ', 'On-Ground Advertisement'), ('Relative', 'Relative'), ('Neighbour', 'Neighbour'), ('Friend', 'Friend'), ('Class Fellow', 'Class Fellow'), ('Any Other', 'Any Other')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
