# Generated by Django 4.0.4 on 2022-11-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0004_skillstudent_information_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstudent',
            name='address',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
