# Generated by Django 4.0.4 on 2022-11-30 04:27

import AdmissionSystem.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0008_alter_skillstudent_photograph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='photograph',
            field=models.ImageField(blank=True, default='/static/default-images/default-student-img.jpg', upload_to=AdmissionSystem.models.SkillStudent.student_directory_path),
        ),
    ]
