# Generated by Django 4.0.4 on 2022-11-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0009_alter_skillstudent_photograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposition',
            name='student',
        ),
        migrations.RemoveField(
            model_name='shortcoursename',
            name='course_duration',
        ),
        migrations.RemoveField(
            model_name='shortcoursename',
            name='student',
        ),
    ]
