# Generated by Django 4.0.4 on 2022-12-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
