# Generated by Django 4.0.4 on 2022-12-01 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdmissionSystem', '0012_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Intersex', 'Intersex')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='pre_qualification',
            field=models.CharField(choices=[('Matric', 'Matric'), ('O-Levels', 'O-Levels'), ('A-Levels', 'A-Levels'), ('Inter', 'Inter'), ('ADP', 'ADP'), ('BS', 'BS'), ('BE', 'BE'), ('Masters', 'Masters'), ('M.Phil', 'M.Phil'), ('PhD', 'PhD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='program_of_interest',
            field=models.CharField(choices=[('Artifical Intelligence', 'Artifical Intelligence'), ('Big Data', 'Big Data'), ('Blockchain Programming', 'Blockchain Programming'), ('Graphics Designing', 'Graphics Designing'), ('Graphics and Web Design', 'Graphics and Web Design'), ('Digital Marketing', 'Digital Marketing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='transportation',
            field=models.CharField(choices=[('Personal Conveyance', 'Personal Conveyance'), ('Parent Conveyance', 'Parent Conveyance'), ('Local Transport', 'Local Transport')], max_length=100),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
