# Generated by Django 4.0.4 on 2022-12-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0014_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudy',
            name='CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='end_timings',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='institute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='institute_Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='semester',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='start_timings',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Emergency_Phone_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Father_Phone_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Mother_Phone_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Personal_Phone_no_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Personal_Phone_no_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='course_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.shortcoursename'),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('NAVTTC', 'NAVTTC'), ('PSDF', 'PSDF'), ('TEVTA', 'TEVTA'), ('Digiskill', 'Digiskill'), ('PIAIC', 'PIAIC')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
