# Generated by Django 4.0.4 on 2022-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0017_alter_currentstudy_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
