# Generated by Django 4.0.4 on 2022-12-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0018_alter_shortcoursestaken_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.shortcoursename'),
        ),
    ]
