# Generated by Django 4.0.4 on 2022-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0019_alter_shortcoursestaken_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillstudent',
            name='updated_by',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='institute',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='institute_Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currentstudy',
            name='semester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Emergency_Phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Father_Phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Mother_Phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Personal_Phone_no_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='Personal_Phone_no_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='course_type',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('NAVTTC', 'NAVTTC'), ('PSDF', 'PSDF'), ('TEVTA', 'TEVTA'), ('Digiskill', 'Digiskill'), ('PIAIC', 'PIAIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shortcoursestaken',
            name='institute_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='address',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='computer_at_Home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='domicile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='father_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='form_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Intersex', 'Intersex')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='laptop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='pre_qualification',
            field=models.CharField(blank=True, choices=[('Matric', 'Matric'), ('O-Levels', 'O-Levels'), ('A-Levels', 'A-Levels'), ('Inter', 'Inter'), ('ADP', 'ADP'), ('BS', 'BS'), ('BE', 'BE'), ('Masters', 'Masters'), ('M.Phil', 'M.Phil'), ('PhD', 'PhD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='residencial_status',
            field=models.CharField(blank=True, choices=[('Hostel', 'Hostel'), ('Local', 'Local')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='shift',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], max_length=20, null=True),
        ),
    ]
