# Generated by Django 4.0.4 on 2022-12-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0020_skillstudent_updated_by_alter_currentstudy_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='information_source',
            field=models.CharField(blank=True, choices=[('Random Walk-in', 'Random Walk-in'), ('Social Media', 'Social Media'), ('By Reference', 'By Reference'), ('Electronic Media', 'Electronic Media'), ('On-Ground Advertisement ', 'On-Ground Advertisement'), ('Relative', 'Relative'), ('Neighbour', 'Neighbour'), ('Friend', 'Friend'), ('Class Fellow', 'Class Fellow'), ('Any Other', 'Any Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='pre_qualification',
            field=models.CharField(choices=[('Matric', 'Matric'), ('O-Levels', 'O-Levels'), ('A-Levels', 'A-Levels'), ('Inter', 'Inter'), ('ADP', 'ADP'), ('BS', 'BS'), ('BE', 'BE'), ('Masters', 'Masters'), ('M.Phil', 'M.Phil'), ('PhD', 'PhD')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='program_of_interest',
            field=models.CharField(blank=True, choices=[('Artifical Intelligence', 'Artifical Intelligence'), ('Big Data', 'Big Data'), ('Blockchain Programming', 'Blockchain Programming'), ('Graphics Designing', 'Graphics Designing'), ('Graphics and Web Design', 'Graphics and Web Design'), ('Digital Marketing', 'Digital Marketing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='transportation',
            field=models.CharField(blank=True, choices=[('Personal Conveyance', 'Personal Conveyance'), ('Parent Conveyance', 'Parent Conveyance'), ('Local Transport', 'Local Transport')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='updated_by',
            field=models.CharField(max_length=100),
        ),
    ]
