# Generated by Django 4.0.4 on 2022-12-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0021_alter_skillstudent_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
