# Generated by Django 4.0.4 on 2022-12-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0022_alter_skillstudent_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='admission_status',
            field=models.CharField(choices=[('Contacted Virtually', 'Contacted Virtually'), ('Reception Appearance', 'Reception Interview'), ('Internal Interview', 'Internal Interview'), ('External Interview', 'External Interview'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Drop out', 'Drop out'), ('Passed out', 'Passed out')], default='Pending', max_length=100),
        ),
    ]
