# Generated by Django 4.0.4 on 2022-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0025_alter_currentstudy_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcoursename',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shortcoursename',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
