# Generated by Django 4.0.6 on 2022-12-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0029_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentstudy',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent'),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='student',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent'),
        ),
    ]
