# Generated by Django 4.0.6 on 2022-12-26 05:25

import AdmissionSystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0030_alter_currentstudy_student_alter_phoneno_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to=AdmissionSystem.models.Document.student_directory_path)),
                ('original_held', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ConventionalStudent',
        ),
        migrations.RenameField(
            model_name='skillstudent',
            old_name='cnic_or_B_form_No',
            new_name='b_form',
        ),
        migrations.AddField(
            model_name='skillstudent',
            name='cnic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='admission_status',
            field=models.CharField(choices=[('Contacted Virtually', 'Contacted Virtually'), ('Reception Appearance', 'Reception Interview'), ('Internal Interview', 'Internal Interview'), ('External Interview', 'External Interview'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Awaiting', 'Awaiting'), ('Drop out', 'Drop out'), ('Passed out', 'Passed out')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AdmissionSystem.documenttype'),
        ),
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent'),
        ),
    ]
