# Generated by Django 4.0.6 on 2022-12-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0031_document_documenttype_delete_conventionalstudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillstudent',
            name='admission_status',
            field=models.CharField(choices=[('Contacted Virtually', 'Contacted Virtually'), ('Reception Appearance', 'Reception Interview'), ('Internal Interview', 'Internal Interview'), ('External Interview', 'External Interview'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Awaiting', 'Awaiting'), ('Drop out', 'Drop out'), ('Passed out', 'Passed out')], max_length=100),
        ),
    ]
