# Generated by Django 4.0.6 on 2022-12-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0032_alter_skillstudent_admission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBatchNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_batch_no', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseConductingBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_conducting_body_name', models.CharField(max_length=50)),
                ('course_conducting_body_abbreviation', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_abbreviation', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_qualification_name', models.CharField(blank=True, max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='admission_status',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='date_applied',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='form_no',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='program_of_interest',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='shift',
        ),
        migrations.AddField(
            model_name='skillstudent',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(default='DOC', on_delete=django.db.models.deletion.SET_DEFAULT, to='AdmissionSystem.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_held',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StudentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent')),
            ],
        ),
        migrations.CreateModel(
            name='RollNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent')),
            ],
        ),
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('admission_status', models.CharField(choices=[('Contacted Virtually', 'Contacted Virtually'), ('Reception Appearance', 'Reception Interview'), ('Internal Interview', 'Internal Interview'), ('External Interview', 'External Interview'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Awaiting', 'Awaiting'), ('Drop out', 'Drop out'), ('Passed out', 'Passed out')], max_length=100)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_batch_id', to='AdmissionSystem.coursebatchno')),
                ('course_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.courseconductingbody')),
                ('course_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.coursename')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_section_id', to='AdmissionSystem.coursebatchno')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.shiftname')),
            ],
        ),
        migrations.CreateModel(
            name='AlreadyRegisteredWithCourseBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('course_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.courseconductingbody')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent')),
            ],
        ),
        migrations.AlterField(
            model_name='skillstudent',
            name='pre_qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.prequalification'),
        ),
    ]
