# Generated by Django 4.0.6 on 2022-12-26 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0033_coursebatchno_courseconductingbody_coursename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillstudent',
            name='pre_qualification',
        ),
        migrations.AddField(
            model_name='skillstudent',
            name='prequalification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.prequalification'),
        ),
    ]
