# Generated by Django 4.0.6 on 2022-12-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0034_remove_skillstudent_pre_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillstudent',
            old_name='prequalification',
            new_name='pre_qualification',
        ),
    ]
