# Generated by Django 4.0.6 on 2022-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0035_rename_prequalification_skillstudent_pre_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftname',
            name='shift_abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
