# Generated by Django 4.0.6 on 2022-12-28 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0036_shiftname_shift_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AdmissionSystem.skillstudent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursebatchno',
            name='course_batch_no',
            field=models.CharField(max_length=50),
        ),
    ]
