# Generated by Django 4.0.6 on 2022-12-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0038_alter_courseapplication_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneno',
            old_name='Emergency_Phone_no',
            new_name='emergency_phone_no',
        ),
        migrations.RenameField(
            model_name='phoneno',
            old_name='Father_Phone_no',
            new_name='father_phone_no',
        ),
        migrations.RenameField(
            model_name='phoneno',
            old_name='Mother_Phone_no',
            new_name='mother_phone_no',
        ),
        migrations.RenameField(
            model_name='phoneno',
            old_name='Personal_Phone_no_1',
            new_name='personal_phone_no_1',
        ),
        migrations.RenameField(
            model_name='phoneno',
            old_name='Personal_Phone_no_2',
            new_name='personal_phone_no_2',
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='created_by',
            field=models.CharField(default='abdullah', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentavailability',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
