# Generated by Django 4.0.6 on 2022-12-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0039_rename_emergency_phone_no_phoneno_emergency_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AdmissionSystem.jobposition'),
        ),
    ]
