# Generated by Django 4.0.6 on 2023-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionSystem', '0042_alter_currentstudy_student_alter_phoneno_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_person_at_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
